### ISSUE TITLE
Differences inside objects are not properly detected

### ISSUE THREAD

**Issue by saibotsivad** [saibotsivad/difference-accumulator#4]
## what happens

Consider this example:

```js
const accumulator = require('difference-accumulator')
const acc = accumulator({ a: { b: 'x', c: 'y' } })
```

If we accumulate a change on the object, the difference is collected:

```js
acc.accumulate({ a: { c: 'z' } })
acc.difference() // => { a: { c: 'z' } }
```

However, if we then accumulate a reverse change on the object, the difference is _not_ collected:

```js
acc.accumulate({ a: { c: 'y' } })
acc.difference() // => { a: { c: 'y' } }
```

## what I expect to happen

My expectation is that the reversed change should yield an empty difference:

```js
const accumulator = require('difference-accumulator')
const acc = accumulator({ a: { b: 'x', c: 'y' } })
acc.accumulate({ a: { c: 'z' } })
acc.difference() // => { a: { c: 'z' } }
acc.accumulate({ a: { c: 'y' } })
acc.difference() // => {}
```

**Comment by TehShrike** [comment]
Right now, the default diff/merge functions don't recurse at all.  They only operate on the properties of the root object passed in.

So, it doesn't care at all if the `a` object has a`c` property or a `b` property, or what their values are - it just cares if `a`'s [identity](https://github.com/saibotsivad/difference-accumulator/blob/b5665509febe69ce9ba5f8f3c1d573abcfea1c82/index.js#L28) matches.

If you want to start caring about comparing objects recursively, merging and diffing gets a lot harder.  You could use [deepmerge](https://github.com/KyleAMathews/deepmerge) and implement a diffing function based on [is-mergeable-object](https://github.com/TehShrike/is-mergeable-object), pass those in, and see if that matches your expectations when it comes to comparing objects recursively.

**Comment by saibotsivad** [comment]
That's a good point, diffing/merging arbitrarily deep objects gets really complicated.

Now that you point that out, I guess I'm not comfortable with adding that weight to this module, especially since you can pass in your own diffing function. I think I'll find or make the thing I want and leave a link to that in the README.
